<?php

$_MAG_DATA["get_localization"] = array();
$_MAG_DATA["get_localization"]["weather_comfort"] = "Комфортно";
$_MAG_DATA["get_localization"]["weather_pressure"] = "Давление";
$_MAG_DATA["get_localization"]["weather_mmhg"] = "mm Hg";
$_MAG_DATA["get_localization"]["weather_wind"] = "Ветер";
$_MAG_DATA["get_localization"]["weather_speed"] = "m/s";
$_MAG_DATA["get_localization"]["weather_humidity"] = "Влажность";
$_MAG_DATA["get_localization"]["current_weather_unavailable"] = "В данный момент погода не доступна";
$_MAG_DATA["get_localization"]["current_weather_not_configured"] = "Виджет погоды не настроен";
$_MAG_DATA["get_localization"]["karaoke_view"] = "СМОТРЕТЬ";
$_MAG_DATA["get_localization"]["karaoke_sort"] = "СОРТИРОВАТЬ";
$_MAG_DATA["get_localization"]["karaoke_search"] = "ПОИСК";
$_MAG_DATA["get_localization"]["karaoke_sampling"] = "ВЫБОР";
$_MAG_DATA["get_localization"]["karaoke_by_letter"] = "ПО БУКВАМ";
$_MAG_DATA["get_localization"]["karaoke_by_performer"] = "ПО ИМЕНИ";
$_MAG_DATA["get_localization"]["karaoke_by_title"] = "ПО НАЗВАНИЮ";
$_MAG_DATA["get_localization"]["karaoke_title"] = "КАРАОКЕ";
$_MAG_DATA["get_localization"]["layer_page"] = "СТРАНИЦА";
$_MAG_DATA["get_localization"]["layer_from"] = "ИЗ";
$_MAG_DATA["get_localization"]["layer_found"] = "НАЙДЕНО";
$_MAG_DATA["get_localization"]["layer_records"] = "ЗАПИСИ";
$_MAG_DATA["get_localization"]["layer_loading"] = "ЗАГРУЗКА...";
$_MAG_DATA["get_localization"]["Loading..."] = "Загрузка...";
$_MAG_DATA["get_localization"]["mbrowser_title"] = "Медия Проводник";
$_MAG_DATA["get_localization"]["mbrowser_connected"] = "подключён";
$_MAG_DATA["get_localization"]["mbrowser_disconnected"] = "отключён";
$_MAG_DATA["get_localization"]["mbrowser_not_found"] = "не найдено";
$_MAG_DATA["get_localization"]["usb_drive"] = "USB носитель";
$_MAG_DATA["get_localization"]["player_limit_notice"] = "Кол-вол подключений огроничено. <br> Попробуйте позже";
$_MAG_DATA["get_localization"]["player_file_missing"] = "Файл отсутсует";
$_MAG_DATA["get_localization"]["player_server_error"] = "Ошибка сервера";
$_MAG_DATA["get_localization"]["player_access_denied"] = "В доступе отказано";
$_MAG_DATA["get_localization"]["player_server_unavailable"] = "Сервер на доступен";
$_MAG_DATA["get_localization"]["player_series"] = "часть";
$_MAG_DATA["get_localization"]["player_track"] = "Трэк";
$_MAG_DATA["get_localization"]["player_off"] = "Откл";
$_MAG_DATA["get_localization"]["player_subtitle"] = "Субтитры";
$_MAG_DATA["get_localization"]["player_claim"] = "Пожаловаться";
$_MAG_DATA["get_localization"]["player_on_sound"] = "на звук";
$_MAG_DATA["get_localization"]["player_on_video"] = "на видео";
$_MAG_DATA["get_localization"]["player_audio"] = "Аудио";
$_MAG_DATA["get_localization"]["player_ty"] = "Спасибо за ваше замечанеи.";
$_MAG_DATA["get_localization"]["series_by_one_play"] = "одна серия";
$_MAG_DATA["get_localization"]["series_continuously_play"] = "подряд";
$_MAG_DATA["get_localization"]["aspect_fit"] = "вместить";
$_MAG_DATA["get_localization"]["aspect_big"] = "зум";
$_MAG_DATA["get_localization"]["aspect_opt"] = "оптимально";
$_MAG_DATA["get_localization"]["aspect_exp"] = "растянуть";
$_MAG_DATA["get_localization"]["aspect_cmb"] = "комбинировано";
$_MAG_DATA["get_localization"]["radio_title"] = "РАДИО";
$_MAG_DATA["get_localization"]["radio_sort"] = "СОРТИРОВКА";
$_MAG_DATA["get_localization"]["radio_favorite"] = "ИЗБРАНОЕ";
$_MAG_DATA["get_localization"]["radio_search"] = "ПОИСК";
$_MAG_DATA["get_localization"]["radio_by_number"] = "по номеру";
$_MAG_DATA["get_localization"]["radio_by_title"] = "по названию";
$_MAG_DATA["get_localization"]["radio_only_favorite"] = "только избраное";
$_MAG_DATA["get_localization"]["radio_fav_add"] = "добавить";
$_MAG_DATA["get_localization"]["radio_fav_del"] = "удалить";
$_MAG_DATA["get_localization"]["radio_search_box"] = "ПОИСК";
$_MAG_DATA["get_localization"]["tv_view"] = "ПРСМОТР";
$_MAG_DATA["get_localization"]["tv_sort"] = "СОРТИРОВКА";
$_MAG_DATA["get_localization"]["favorite"] = "ИЗБРАНОЕ";
$_MAG_DATA["get_localization"]["tv_favorite"] = "ИЗБРАНОЕ";
$_MAG_DATA["get_localization"]["tv_move"] = "ПЕРЕМЕСТИТЬ";
$_MAG_DATA["get_localization"]["tv_by_number"] = "по номеру";
$_MAG_DATA["get_localization"]["tv_by_title"] = "по названию";
$_MAG_DATA["get_localization"]["tv_only_favorite"] = "только избраные";
$_MAG_DATA["get_localization"]["tv_only_hd"] = "только HD";
$_MAG_DATA["get_localization"]["tv_list"] = "лист";
$_MAG_DATA["get_localization"]["tv_list_w_info"] = "лист + инфо";
$_MAG_DATA["get_localization"]["tv_title"] = "ТВ";
$_MAG_DATA["get_localization"]["vclub_info"] = "информация о фильме";
$_MAG_DATA["get_localization"]["vclub_year"] = "Год";
$_MAG_DATA["get_localization"]["vclub_country"] = "Страна";
$_MAG_DATA["get_localization"]["vclub_genre"] = "Жанр";
$_MAG_DATA["get_localization"]["vclub_length"] = "Длит.";
$_MAG_DATA["get_localization"]["vclub_minutes"] = "мин";
$_MAG_DATA["get_localization"]["vclub_director"] = "Режисёр";
$_MAG_DATA["get_localization"]["vclub_cast"] = "В ролях";
$_MAG_DATA["get_localization"]["vclub_rating"] = "Рейтинг";
$_MAG_DATA["get_localization"]["vclub_age"] = "Возраст";
$_MAG_DATA["get_localization"]["vclub_rating_mpaa"] = "Рейтинг MPAA";
$_MAG_DATA["get_localization"]["vclub_view"] = "ПРОСМОТР";
$_MAG_DATA["get_localization"]["vclub_sort"] = "СОРТИРОВКА";
$_MAG_DATA["get_localization"]["vclub_search"] = "ПОИСК";
$_MAG_DATA["get_localization"]["vclub_fav"] = "ИЗБРАНЫЕ";
$_MAG_DATA["get_localization"]["vclub_other"] = "ДРУГИЕ";
$_MAG_DATA["get_localization"]["vclub_find"] = "НАЙТИ";
$_MAG_DATA["get_localization"]["vclub_by_letter"] = "ПО БУКВЕ";
$_MAG_DATA["get_localization"]["vclub_by_genre"] = "ПО ЖАНРУ";
$_MAG_DATA["get_localization"]["vclub_by_year"] = "ПО ГОДУ";
$_MAG_DATA["get_localization"]["vclub_by_rating"] = "ПО РЕЙТИНГУ";
$_MAG_DATA["get_localization"]["vclub_search_box"] = "поиск";
$_MAG_DATA["get_localization"]["vclub_query_box"] = "отбор";
$_MAG_DATA["get_localization"]["vclub_by_title"] = "по названию";
$_MAG_DATA["get_localization"]["vclub_by_addtime"] = "по добавлению";
$_MAG_DATA["get_localization"]["vclub_top"] = "рейтинг";
$_MAG_DATA["get_localization"]["vclub_only_hd"] = "только HD";
$_MAG_DATA["get_localization"]["vclub_only_favorite"] = "только избраные";
$_MAG_DATA["get_localization"]["vclub_only_purchased"] = "приобретённые";
$_MAG_DATA["get_localization"]["vclub_not_ended"] = "не истёкшие";
$_MAG_DATA["get_localization"]["vclub_list"] = "лист";
$_MAG_DATA["get_localization"]["vclub_list_w_info"] = "лист + информация";
$_MAG_DATA["get_localization"]["vclub_title"] = "ВИДЕОКЛУБ";
$_MAG_DATA["get_localization"]["vclub_purchased"] = "Приобретённые";
$_MAG_DATA["get_localization"]["vclub_rent_expires_in"] = "аренда истекает в";
$_MAG_DATA["get_localization"]["cut_off_msg"] = "Ваша приставка заблокирована.<br/> Обратитесь к провайдеру.";
$_MAG_DATA["get_localization"]["month_arr"] = array("ЯНВАРЬ", "ФЕВРАЛЬ", "МАРТ", "АПРЕЛЬ", "МАЙ", "ИЮНЬ", "ИЮЛЬ", "АВГУСТ", "СЕНТЯБРЬ", "ОКТЯБРЬ", "НОЯБРЬ", "ДЕКАБРЬ");
$_MAG_DATA["get_localization"]["week_arr"] = array("ВОСКРЕСЕНЬЕ", "ПОНЕДЕЛЬНИК", "ВТОРНИК", "СРЕДА", "ЧЕТВЕРГ", "ПЯТНИЦА", "СУБОТА");
$_MAG_DATA["get_localization"]["year"] = "";
$_MAG_DATA["get_localization"]["records_title"] = "ЗАПИСИ";
$_MAG_DATA["get_localization"]["ears_back"] = "<br>Н<br>А<br>З<br>А<br>Д<br>";
$_MAG_DATA["get_localization"]["ears_about_movie"] = "<br>О<br> <br>Ф<br>И<br>Л<br>Ь<br>М<br>Е<br>";
$_MAG_DATA["get_localization"]["ears_tv_guide"] = "<br>Т<br>В<br> <br>Г<br>И<br>Д<br>";
$_MAG_DATA["get_localization"]["ears_about_package"] = "<br>И<br>Н<br>Ф<br>О<br> <br>О<br> <br>П<br>А<br>К<br>Е<br>Т<br>Е<br>";
$_MAG_DATA["get_localization"]["settings_title"] = "НАСТРОЙКИ";
$_MAG_DATA["get_localization"]["parent_settings_cancel"] = "ОТМЕНА";
$_MAG_DATA["get_localization"]["parent_settings_save"] = "СОХРАНИТЬ";
$_MAG_DATA["get_localization"]["parent_settings_old_pass"] = "Текущий пароль";
$_MAG_DATA["get_localization"]["parent_settings_title"] = "РОДИТЕЛЬСКИЕ НАСТРОЙКИ";
$_MAG_DATA["get_localization"]["parent_settings_title_short"] = "РОДИТЕЛЬСКИЕ";
$_MAG_DATA["get_localization"]["parent_settings_new_pass"] = "Новый пароль";
$_MAG_DATA["get_localization"]["parent_settings_repeat_new_pass"] = "Повторите новый пароль";
$_MAG_DATA["get_localization"]["settings_saved"] = "Настройки сохранены";
$_MAG_DATA["get_localization"]["settings_saved_reboot"] = "Настройки сохранены.<br>Для перезагрузки приставки, нажмите ОК.";
$_MAG_DATA["get_localization"]["settings_check_error"] = "Ошибка заполнения полей";
$_MAG_DATA["get_localization"]["settings_saving_error"] = "Ошибка сохранения";
$_MAG_DATA["get_localization"]["localization_settings_title"] = "ЛОКАЛИЗАЦИЯ";
$_MAG_DATA["get_localization"]["localization_label"] = "Язык интерфейса";
$_MAG_DATA["get_localization"]["country_label"] = "Страна";
$_MAG_DATA["get_localization"]["city_label"] = "Город";
$_MAG_DATA["get_localization"]["localization_page_button_info"] = "Используйте кнопки -/+ для навигации по меню.";
$_MAG_DATA["get_localization"]["settings_software_update"] = "ОБНОВЛЕНИЕ ПРОГРАММЫ";
$_MAG_DATA["get_localization"]["update_settings_cancel"] = "ОТМЕНА";
$_MAG_DATA["get_localization"]["update_settings_start_update"] = "НАЧАТЬ ОБНОВЛЕНИЕ";
$_MAG_DATA["get_localization"]["update_from_http"] = "По HTTP";
$_MAG_DATA["get_localization"]["update_from_usb"] = "По USB";
$_MAG_DATA["get_localization"]["update_source"] = "Источник";
$_MAG_DATA["get_localization"]["update_method_select"] = "Выбраный метод";
$_MAG_DATA["get_localization"]["empty"] = "ПУСТО";
$_MAG_DATA["get_localization"]["course_title"] = "Курс на";
$_MAG_DATA["get_localization"]["course_title_nbu"] = "NBU курс для";
$_MAG_DATA["get_localization"]["course_title_cbr"] = "CBR курс для";
$_MAG_DATA["get_localization"]["dayweather_title"] = "ПОГОДА";
$_MAG_DATA["get_localization"]["dayweather_pressure"] = "дав.:";
$_MAG_DATA["get_localization"]["dayweather_mmhg"] = "mm Hg";
$_MAG_DATA["get_localization"]["dayweather_wind"] = "ветер:";
$_MAG_DATA["get_localization"]["dayweather_speed"] = "m/s";
$_MAG_DATA["get_localization"]["infoportal_title"] = "ИНФО ПОРТАЛ";
$_MAG_DATA["get_localization"]["cityinfo_title"] = "ГОРОДСКОЙ ПОРТАЛ";
$_MAG_DATA["get_localization"]["cityinfo_main"] = "аварийный";
$_MAG_DATA["get_localization"]["cityinfo_help"] = "помощь";
$_MAG_DATA["get_localization"]["cityinfo_other"] = "другое";
$_MAG_DATA["get_localization"]["cityinfo_sort"] = "ВИД";
$_MAG_DATA["get_localization"]["horoscope_title"] = "ГОРОСКОП";
$_MAG_DATA["get_localization"]["anecdote_title"] = "АНЕКДОТЫ";
$_MAG_DATA["get_localization"]["anecdote_goto"] = "ПЕРЕЙТИ";
$_MAG_DATA["get_localization"]["anecdote_like"] = "ЛАЙК";
$_MAG_DATA["get_localization"]["anecdote_bookmark"] = "ЗАКЛАДКА";
$_MAG_DATA["get_localization"]["anecdote_to_bookmark"] = "В ЗАКЛАДКИ";
$_MAG_DATA["get_localization"]["anecdote_pagebar_title"] = "АНЕКДОТ";
$_MAG_DATA["get_localization"]["mastermind_title"] = "MASTERMIND";
$_MAG_DATA["get_localization"]["mastermind_rules"] = "ПРАВИЛА";
$_MAG_DATA["get_localization"]["mastermind_rating"] = "РЕЙТИНГ";
$_MAG_DATA["get_localization"]["mastermind_bull"] = "B";
$_MAG_DATA["get_localization"]["mastermind_cow"] = "C";
$_MAG_DATA["get_localization"]["mastermind_rules_text"] = "Ваша задача угадать число неповторяющихся четырех цифр, первая из них - не ноль. Каждый Ваше предположение будет по сравнению с числом выдвинул STB. Если вы догадались цифра, но она не стоит на месте, то это корова (С). Если вы догадались, и число, и его расположение, это BULL (Б).";
$_MAG_DATA["get_localization"]["mastermind_move_cursor"] = "Передвигая курсор";
$_MAG_DATA["get_localization"]["mastermind_cell_numbers"] = "Введите цифры в клетки";
$_MAG_DATA["get_localization"]["mastermind_step_confirmation"] = "Подтверждение хода";
$_MAG_DATA["get_localization"]["mastermind_page"] = "Страница";
$_MAG_DATA["get_localization"]["mastermind_history_moves"] = "Просмотр истории ходов";
$_MAG_DATA["get_localization"]["msg_service_off"] = "Сервис не доступен";
$_MAG_DATA["get_localization"]["msg_channel_not_available"] = "Канал не доступен";
$_MAG_DATA["get_localization"]["epg_title"] = "ТВ гид";
$_MAG_DATA["get_localization"]["epg_record"] = "ЗАПИСЬ";
$_MAG_DATA["get_localization"]["epg_remind"] = "НАПОМНИТЬ";
$_MAG_DATA["get_localization"]["epg_memo"] = "Memo";
$_MAG_DATA["get_localization"]["epg_goto_ch"] = "Перейти к каналу";
$_MAG_DATA["get_localization"]["epg_close_msg"] = "закрыть";
$_MAG_DATA["get_localization"]["epg_on_ch"] = "на канале";
$_MAG_DATA["get_localization"]["epg_now_begins"] = "начинается сейчас";
$_MAG_DATA["get_localization"]["epg_on_time"] = "в";
$_MAG_DATA["get_localization"]["epg_started"] = "начало";
$_MAG_DATA["get_localization"]["epg_more"] = "БОЛЬШЕ";
$_MAG_DATA["get_localization"]["epg_category"] = "Категория";
$_MAG_DATA["get_localization"]["epg_director"] = "Режисёр";
$_MAG_DATA["get_localization"]["epg_actors"] = "В ролях";
$_MAG_DATA["get_localization"]["epg_desc"] = "Описание";
$_MAG_DATA["get_localization"]["search_box_languages"] = array("ru");
$_MAG_DATA["get_localization"]["date_format"] = "{0}, {2} {1}, {3}";
$_MAG_DATA["get_localization"]["time_format"] = "{2}:{1} {3}";
$_MAG_DATA["get_localization"]["timezone_label"] = "Временная зонна";
$_MAG_DATA["get_localization"]["ntp_server"] = "NTP Сервер";
$_MAG_DATA["get_localization"]["remote_pvr_del"] = "УДАЛИТЬ";
$_MAG_DATA["get_localization"]["remote_pvr_stop"] = "ОСТАВНОВИТЬ";
$_MAG_DATA["get_localization"]["remote_pvr_del_confirm"] = "Вы действительно хотите удалить эту запись?";
$_MAG_DATA["get_localization"]["remote_pvr_stop_confirm"] = "Вы действительно хотите удалить эту запись?";
$_MAG_DATA["get_localization"]["alert_confirm"] = "Подтвердить";
$_MAG_DATA["get_localization"]["alert_cancel"] = "Отменить";
$_MAG_DATA["get_localization"]["recorder_server_error"] = "Ошибка сервера. Попробуйте позже.";
$_MAG_DATA["get_localization"]["record_duration"] = "ДЛИННА ЗАПИСИ, ч";
$_MAG_DATA["get_localization"]["rest_length_title"] = "СВОБОДНО НА СЕРВЕРЕ, ч";
$_MAG_DATA["get_localization"]["channel_recording_restricted"] = "Запись данного канала запрещена";
$_MAG_DATA["get_localization"]["playback_settings_buffer_size"] = "Размер буфера";
$_MAG_DATA["get_localization"]["playback_settings_time"] = "Время, сек";
$_MAG_DATA["get_localization"]["playback_settings_title"] = "ПРОИГРАТЬ";
$_MAG_DATA["get_localization"]["cancel_btn"] = "ОТМЕНА";
$_MAG_DATA["get_localization"]["settings_cancel"] = "ОТМЕНА";
$_MAG_DATA["get_localization"]["playback_settings_cancel"] = "ОТМЕНА";
$_MAG_DATA["get_localization"]["exit_btn"] = "ВЫХОД";
$_MAG_DATA["get_localization"]["yes_btn"] = "ДА";
$_MAG_DATA["get_localization"]["close_btn"] = "ЗАКРЫТЬ";
$_MAG_DATA["get_localization"]["ok_btn"] = "OK";
$_MAG_DATA["get_localization"]["pay_btn"] = "ОПЛАТА";
$_MAG_DATA["get_localization"]["play_btn"] = "ИРАТЬ";
$_MAG_DATA["get_localization"]["start_btn"] = "СТАРТ";
$_MAG_DATA["get_localization"]["add_btn"] = "ДОБАВИТЬ";
$_MAG_DATA["get_localization"]["settings_save"] = "СОХРАНИТЬ";
$_MAG_DATA["get_localization"]["playback_settings_save"] = "СОХРАНИТЬ";
$_MAG_DATA["get_localization"]["audio_out"] = "Аудио выход";
$_MAG_DATA["get_localization"]["audio_out_analog"] = "Только аналоговый";
$_MAG_DATA["get_localization"]["audio_out_analog_spdif"] = "Аналоговый и S/PDIF двух канальный PCM";
$_MAG_DATA["get_localization"]["audio_out_spdif"] = "S/PDIF raw or 2-channel PCM";
$_MAG_DATA["get_localization"]["game"] = "ИГРА";
$_MAG_DATA["get_localization"]["downloads_title"] = "ЗАГРУЗКИ";
$_MAG_DATA["get_localization"]["not_found_mounted_devices"] = "Не найдено устройство";
$_MAG_DATA["get_localization"]["downloads_add_download"] = "Добавить загрузку";
$_MAG_DATA["get_localization"]["downloads_device"] = "Устройство";
$_MAG_DATA["get_localization"]["downloads_file_name"] = "Название файла";
$_MAG_DATA["get_localization"]["downloads_ok"] = "Ok";
$_MAG_DATA["get_localization"]["downloads_cancel"] = "Отмена";
$_MAG_DATA["get_localization"]["downloads_create"] = "СОЗДАТЬ";
$_MAG_DATA["get_localization"]["downloads_move_up"] = "ВВЕРХ";
$_MAG_DATA["get_localization"]["downloads_move_down"] = "ВНИЗ";
$_MAG_DATA["get_localization"]["downloads_delete"] = "УДАЛИТЬ";
$_MAG_DATA["get_localization"]["downloads_record"] = "ЗАПИСЬ";
$_MAG_DATA["get_localization"]["downloads_download"] = "ЗАГРУЗИТЬ";
$_MAG_DATA["get_localization"]["downloads_record_and_file"] = "ЗАПИСЬ И ФАЙЛ";
$_MAG_DATA["get_localization"]["playback_limit_title"] = "Время проигрывания";
$_MAG_DATA["get_localization"]["playback_limit_off"] = "Без ограничения";
$_MAG_DATA["get_localization"]["playback_hours"] = "часов";
$_MAG_DATA["get_localization"]["playback_limit_reached"] = "Достигнута максимальная точка непрерывного просмотра. Для продолжения нажмите ОК.";
$_MAG_DATA["get_localization"]["common_settings_title"] = "ГЛАВНЫЕ";
$_MAG_DATA["get_localization"]["screensaver_delay_title"] = "Интервал Хранителя Экрана";
$_MAG_DATA["get_localization"]["screensaver_off"] = "Отменить";
$_MAG_DATA["get_localization"]["screensaver_minutes"] = "мин";
$_MAG_DATA["get_localization"]["demo_video_title"] = "ДЕМО ВИДЕО";
$_MAG_DATA["get_localization"]["account_info_title"] = "УЧЁТНАЯ ЗАПИСЬ";
$_MAG_DATA["get_localization"]["coming_soon"] = "СКОРО";
$_MAG_DATA["get_localization"]["account_info"] = "ИНФОРМАЦИЯ";
$_MAG_DATA["get_localization"]["account_payment"] = "ОПЛАТА";
$_MAG_DATA["get_localization"]["account_pay"] = "ОПЛАТИТЬ";
$_MAG_DATA["get_localization"]["account_agreement"] = "СОГЛАШЕНИЕ";
$_MAG_DATA["get_localization"]["account_terms"] = "ПРАВИЛА ПОЛЬЗОВАНИЯ";
$_MAG_DATA["get_localization"]["demo_video"] = "Видео Инструкция";
$_MAG_DATA["get_localization"]["tv_quality"] = "КАЧЕСТВО";
$_MAG_DATA["get_localization"]["tv_quality_low"] = "НИЗКОЕ";
$_MAG_DATA["get_localization"]["tv_quality_medium"] = "СРЕДНЕЕ";
$_MAG_DATA["get_localization"]["tv_quality_high"] = "ВЫСОКОЕ";
$_MAG_DATA["get_localization"]["tv_fav_add"] = "добавить";
$_MAG_DATA["get_localization"]["tv_fav_del"] = "удалить";
$_MAG_DATA["get_localization"]["internet"] = "интернет";
$_MAG_DATA["get_localization"]["network_status_title"] = "СТАТУС СЕТИ";
$_MAG_DATA["get_localization"]["network_status_refresh"] = "ОБНОВИТЬ";
$_MAG_DATA["get_localization"]["test_speed"] = "Проверка скорости";
$_MAG_DATA["get_localization"]["speedtest_testing"] = "проверяю...";
$_MAG_DATA["get_localization"]["speedtest_error"] = "ошибка";
$_MAG_DATA["get_localization"]["speedtest_waiting"] = "ожидаю...";
$_MAG_DATA["get_localization"]["lan_up"] = "ВВЕРХ";
$_MAG_DATA["get_localization"]["lan_down"] = "ВНИЗ";
$_MAG_DATA["get_localization"]["download_stopped"] = "остановлено";
$_MAG_DATA["get_localization"]["download_waiting_queue"] = "ожидаю в очереди";
$_MAG_DATA["get_localization"]["download_running"] = "работаю";
$_MAG_DATA["get_localization"]["download_completed"] = "завершено";
$_MAG_DATA["get_localization"]["download_temporary_error"] = "временная ошибка";
$_MAG_DATA["get_localization"]["download_permanent_error"] = "постоянная ошибка";
$_MAG_DATA["get_localization"]["auth_title"] = "Аутентификация";
$_MAG_DATA["get_localization"]["auth_login"] = "Пользователь";
$_MAG_DATA["get_localization"]["auth_password"] = "Пароль";
$_MAG_DATA["get_localization"]["auth_error"] = "Ошибка";
$_MAG_DATA["get_localization"]["play_or_download"] = "Проиграть или скачать данную ссылку?";
$_MAG_DATA["get_localization"]["player_play"] = "Проиграть";
$_MAG_DATA["get_localization"]["player_download"] = "Скачать";
$_MAG_DATA["get_localization"]["play_all"] = "Проиграть все";
$_MAG_DATA["get_localization"]["on"] = "вкл";
$_MAG_DATA["get_localization"]["off"] = "выкл";
$_MAG_DATA["get_localization"]["smb_auth"] = "Аутентификация Сети";
$_MAG_DATA["get_localization"]["smb_username"] = "Логин";
$_MAG_DATA["get_localization"]["smb_password"] = "Проль";
$_MAG_DATA["get_localization"]["exit_title"] = "Вы действительно хотите выйти?";
$_MAG_DATA["get_localization"]["identical_download_exist"] = "В данной момент происходит загрузка с данного сервера";
$_MAG_DATA["get_localization"]["alert_form_title"] = "Внимание";
$_MAG_DATA["get_localization"]["confirm_form_title"] = "Подтвердить";
$_MAG_DATA["get_localization"]["notice_form_title"] = "Заметка";
$_MAG_DATA["get_localization"]["select_form_title"] = "Выбор";
$_MAG_DATA["get_localization"]["media_favorites"] = "Избраные";
$_MAG_DATA["get_localization"]["stb_type_not_supported"] = "Ваша приставка не поддерживается";
$_MAG_DATA["get_localization"]["Phone"] = "Телефон";
$_MAG_DATA["get_localization"]["Tariff plan"] = "Тарифный план";
$_MAG_DATA["get_localization"]["User"] = "Пользователь";
$_MAG_DATA["get_localization"]["SERVICES MANAGEMENT"] = "УПРАВЛЕНИЕ УСЛУГАМИ";
$_MAG_DATA["get_localization"]["SUBSCRIBE"] = "ПОДПИСАТЬСЯ";
$_MAG_DATA["get_localization"]["UNSUBSCRIBE"] = "ОТПИСАТЬСЯ";
$_MAG_DATA["get_localization"]["package_info_title"] = "ИНФОРМАЦИЯ О ПАКЕТЕ";
$_MAG_DATA["get_localization"]["package_type"] = "Тип";
$_MAG_DATA["get_localization"]["package_content"] = "Содержимое";
$_MAG_DATA["get_localization"]["package_description"] = "Описание";
$_MAG_DATA["get_localization"]["confirm_service_subscribe_text"] = "Вы действительно хотите подписаться на данную услугу?";
$_MAG_DATA["get_localization"]["confirm_service_unsubscribe_text"] = "Вы действительно хотите отписаться от данной услуги?";
$_MAG_DATA["get_localization"]["confirm_service_price_text"] = "Стоимость услуги {0}";
$_MAG_DATA["get_localization"]["service_subscribe_success"] = "Вы успешно подписались на данную услугу.";
$_MAG_DATA["get_localization"]["service_unsubscribe_success"] = "Вы успешно отписались от данной услуги.";
$_MAG_DATA["get_localization"]["service_subscribe_success_reboot"] = "Вы успешно подписались на услугу. Присавка будет перезагружена.";
$_MAG_DATA["get_localization"]["service_unsubscribe_success_reboot"] = "Вы успешно отписались от услуги. Присавка будет перезагружена.";
$_MAG_DATA["get_localization"]["service_subscribe_fail"] = "Возникла ошибка при управление подписками.";
$_MAG_DATA["get_localization"]["service_subscribe_server_error"] = "Ошибка сервера. Попробуйте позже.";
$_MAG_DATA["get_localization"]["package_price_measurement"] = "USD";
$_MAG_DATA["get_localization"]["rent_movie_text"] = "Вы действительно хотите купить данный фильм?";
$_MAG_DATA["get_localization"]["rent_movie_price_text"] = "Стоимость {0}";
$_MAG_DATA["get_localization"]["rent_duration_text"] = "Время ренты: {0}h";
$_MAG_DATA["get_localization"]["Account number"] = "Номер счёта";
$_MAG_DATA["get_localization"]["End date"] = "Дата окончания";
$_MAG_DATA["get_localization"]["3D mode"] = "3D mode";
$_MAG_DATA["get_localization"]["mode {0}"] = "mode {0}";
$_MAG_DATA["get_localization"]["no epg"] = "нет ЕПГ";
$_MAG_DATA["get_localization"]["wrong epg"] = "не правильный ЕПГ";
$_MAG_DATA["get_localization"]["iso_title"] = "Название";
$_MAG_DATA["get_localization"]["error_channel_nothing_to_play"] = "Канал не доступен";
$_MAG_DATA["get_localization"]["error_channel_limit"] = "Канал временно не доступен";
$_MAG_DATA["get_localization"]["error_channel_not_available_for_zone"] = "Канал не доступен в данном регионе";
$_MAG_DATA["get_localization"]["error_channel_link_fault"] = "Канал не доступен. Ошибка сервера.";
$_MAG_DATA["get_localization"]["error_channel_access_denied"] = "В доступе отказано.";
$_MAG_DATA["get_localization"]["blocking_account_info"] = "Инфо. о учётной записи";
$_MAG_DATA["get_localization"]["blocking_account_payment"] = "Оплата";
$_MAG_DATA["get_localization"]["blocking_account_reboot"] = "Перегрузить Портал";
$_MAG_DATA["get_localization"]["archive_continue_playing_text"] = "Продолжить проигрывание?";
$_MAG_DATA["get_localization"]["archive_yes"] = "ДА";
$_MAG_DATA["get_localization"]["archive_no"] = "НЕТ";
$_MAG_DATA["get_localization"]["time_shift_exit_confirm_text"] = "Хотите выйти из режима Time Shift?";
$_MAG_DATA["get_localization"]["mbrowser_sort_by_name"] = "по названию";
$_MAG_DATA["get_localization"]["mbrowser_sort_by_date"] = "по дате";
$_MAG_DATA["get_localization"]["Connection problem"] = "Проблеммы подключения";
$_MAG_DATA["get_localization"]["Authentication problem"] = "Проблеммы аутентификации";
$_MAG_DATA["get_localization"]["Account balance"] = "Балланс на счету";
$_MAG_DATA["get_localization"]["remote_pvr_confirm_text"] = "Начать запись на сервер?";
$_MAG_DATA["get_localization"]["remote_deferred_pvr_confirm_text"] = "Вы действительно хотите задать время записи на сервер?";
$_MAG_DATA["get_localization"]["pvr_target_select_text"] = "Укажите куда сохранить запись";
$_MAG_DATA["get_localization"]["usb_target_btn"] = "На флеш диск";
$_MAG_DATA["get_localization"]["server_target_btn"] = "На сервер";
$_MAG_DATA["get_localization"]["save_path"] = "Путь";
$_MAG_DATA["get_localization"]["file_name"] = "Название";
$_MAG_DATA["get_localization"]["usb_device"] = "Флеш Диск";
$_MAG_DATA["get_localization"]["rec_stop_msg"] = "Запись прервана {0} на канале {1}";
$_MAG_DATA["get_localization"]["rec_file_missing"] = "Файл записи отсутсвует";
$_MAG_DATA["get_localization"]["rec_not_ended"] = "Запись ещё не завершена";
$_MAG_DATA["get_localization"]["rec_channel_has_scheduled_recording"] = "Даннаом канале уже задана передача для записи";
$_MAG_DATA["get_localization"]["pvr_error_wrong_param"] = "Ошибка PVR: Не правильный параметр";
$_MAG_DATA["get_localization"]["pvr_error_memory"] = "Ошибка PVR: Не достаточно памяти для завершения операции";
$_MAG_DATA["get_localization"]["pvr_error_duration"] = "Ошибка PVR: Неправильный диапазон записи";
$_MAG_DATA["get_localization"]["pvr_error_not_found"] = "Ошибка PVR: Задание не найдено";
$_MAG_DATA["get_localization"]["pvr_error_wrong_filename"] = "Ошибка PVR: Не правильное имя файла";
$_MAG_DATA["get_localization"]["pvr_error_record_exist"] = "Ошибка PVR: Файл записи уже существует";
$_MAG_DATA["get_localization"]["pvr_error_url_open_error"] = "Ошибка PVR: Ошибка открытия ссылки";
$_MAG_DATA["get_localization"]["pvr_error_file_open_error"] = "Ошибка PVR: Ошибка открытия файла";
$_MAG_DATA["get_localization"]["pvr_error_rec_limit"] = "Ошибка PVR: Привышено максимальное кол-во одновременных записей.";
$_MAG_DATA["get_localization"]["pvr_error_end_of_stream"] = "Ошибка PVR: Окончание потока";
$_MAG_DATA["get_localization"]["pvr_error_file_write_error"] = "Ошибка PVR: Ошибка записи файла";
$_MAG_DATA["get_localization"]["pvr_start_time"] = "Время начала";
$_MAG_DATA["get_localization"]["pvr_end_time"] = "Время окончания";
$_MAG_DATA["get_localization"]["pvr_duration"] = "Длительность";
$_MAG_DATA["get_localization"]["rec_options_form_title"] = "Записываю";
$_MAG_DATA["get_localization"]["local_pvr_interrupted"] = "Запись на флеш USB устройство прервана";
$_MAG_DATA["get_localization"]["parent_password_error"] = "Не правильно";
$_MAG_DATA["get_localization"]["parent_password_title"] = "Род. Контроль";
$_MAG_DATA["get_localization"]["password_label"] = "Пароль";
$_MAG_DATA["get_localization"]["encoding_label"] = "Кодирование";
$_MAG_DATA["get_localization"]["network_folder"] = "Сетевая папка";
$_MAG_DATA["get_localization"]["server_ip"] = "IP адресс";
$_MAG_DATA["get_localization"]["server_path"] = "Путь";
$_MAG_DATA["get_localization"]["local_folder"] = "Локальная папка";
$_MAG_DATA["get_localization"]["server_type"] = "Тип";
$_MAG_DATA["get_localization"]["server_login"] = "Логин";
$_MAG_DATA["get_localization"]["server_password"] = "Пароль";
$_MAG_DATA["get_localization"]["add_folder"] = "ДОБАВИТЬ";
$_MAG_DATA["get_localization"]["server_ip_placeholder"] = "Адресс сервера";
$_MAG_DATA["get_localization"]["server_path_placeholder"] = "Путь к папке";
$_MAG_DATA["get_localization"]["local_folder_placeholder"] = "Название папки в избраное";
$_MAG_DATA["get_localization"]["error"] = "ошибка";
$_MAG_DATA["get_localization"]["mount_failed"] = "Монтировка не удалась";
$_MAG_DATA["get_localization"]["ad_skip"] = "ПРОПУСТИТЬ";
$_MAG_DATA["get_localization"]["commercial"] = "РЕКЛАМА";
$_MAG_DATA["get_localization"]["videoClockTitle"] = "Часа";
$_MAG_DATA["get_localization"]["videoClock_off"] = "Спрятано";
$_MAG_DATA["get_localization"]["videoClock_upRight"] = "С права в верху";
$_MAG_DATA["get_localization"]["videoClock_upLeft"] = "С лева в верху";
$_MAG_DATA["get_localization"]["videoClock_downRight"] = "С права в низу";
$_MAG_DATA["get_localization"]["videoClock_downLeft"] = "С лева в низу";
$_MAG_DATA["get_localization"]["settings_unavailable"] = "Секция настроек в данный момент не доступна";
$_MAG_DATA["get_localization"]["no_dvb_channels_title"] = "Нет доступных каналов";
$_MAG_DATA["get_localization"]["go_to_dvb_settings"] = "Вы можете настроить DVB каналы в настройках меню";
$_MAG_DATA["get_localization"]["apps_title"] = "Аппликации";
$_MAG_DATA["get_localization"]["coming_soon_video"] = "Видео будет доступно скоро";
$_MAG_DATA["get_profile"]["name"] = "";
$_MAG_DATA["get_profile"]["sname"] = "";
$_MAG_DATA["get_profile"]["pass"] = "";
$_MAG_DATA["get_profile"]["additional_services_on"] = "";
$_MAG_DATA["get_profile"]["operator_id"] = "0";
$_MAG_DATA["get_profile"]["storage_name"] = "";
$_MAG_DATA["get_profile"]["phone"] = "";
$_MAG_DATA["get_profile"]["tv_quality"] = "high";
$_MAG_DATA["get_profile"]["fname"] = "nets";
$_MAG_DATA["get_profile"]["login"] = "";
$_MAG_DATA["get_profile"]["password"] = "";
$_MAG_DATA["get_profile"]["num_banks"] = "0";
$_MAG_DATA["get_profile"]["tariff_plan_id"] = "1";
$_MAG_DATA["get_profile"]["comment"] = "";
$_MAG_DATA["get_profile"]["now_playing_link_id"] = "0";
$_MAG_DATA["get_profile"]["now_playing_streamer_id"] = "0";
$_MAG_DATA["get_profile"]["just_started"] = "1";
$_MAG_DATA["get_profile"]["verified"] = "0";
$_MAG_DATA["get_profile"]["pri_audio_lang"] = "";
$_MAG_DATA["get_profile"]["sec_audio_lang"] = "";
$_MAG_DATA["get_profile"]["pri_subtitle_lang"] = "";
$_MAG_DATA["get_profile"]["sec_subtitle_lang"] = "";
$_MAG_DATA["get_profile"]["hw_version"] = "undefined";
$_MAG_DATA["get_profile"]["storages"] = "";
$_MAG_DATA["get_profile"]["last_itv_id"] = "1";
$_MAG_DATA["get_profile"]["updated"] = "";
$_MAG_DATA["get_profile"]["web_proxy_host"] = "";
$_MAG_DATA["get_profile"]["web_proxy_port"] = "";
$_MAG_DATA["get_profile"]["web_proxy_user"] = "";
$_MAG_DATA["get_profile"]["web_proxy_pass"] = "";
$_MAG_DATA["get_profile"]["web_proxy_exclude_list"] = "";
$_MAG_DATA["get_profile"]["demo_video_url"] = "";
$_MAG_DATA["get_profile"]["tv_quality_filter"] = "";
$_MAG_DATA["get_profile"]["use_embedded_settings"] = "";
$_MAG_DATA["get_profile"]["is_moderator"] = "";
$_MAG_DATA["get_profile"]["timeslot_ratio"] = "0.94530244530245";
$_MAG_DATA["get_profile"]["timeslot"] = "113.43629343629";
$_MAG_DATA["get_profile"]["kinopoisk_rating"] = "1";
$_MAG_DATA["get_profile"]["enable_tariff_plans"] = "1";
$_MAG_DATA["get_profile"]["enable_buffering_indication"] = "1";
$_MAG_DATA["get_profile"]["allowed_stb_types_for_local_recording"] = array("mag245", "mag250", "mag255", "mag270", "mag275", "aurahd");
$_MAG_DATA["get_profile"]["strict_stb_type_check"] = "";
$_MAG_DATA["get_profile"]["cas_params"] = "";
$_MAG_DATA["get_profile"]["enable_hdmi_events_handler"] = "1";
$_MAG_DATA["get_profile"]["cas_additional_params"] = "";
$_MAG_DATA["get_profile"]["cas_ini_file"] = "";
$_MAG_DATA["get_profile"]["logarithm_volume_control"] = "1";
$_MAG_DATA["get_profile"]["allow_subscription_from_stb"] = "1";
$_MAG_DATA["get_profile"]["deny_720p_gmode_720_on_mag200"] = "1";
$_MAG_DATA["get_profile"]["enable_arrow_keys_setpos"] = "1";
$_MAG_DATA["get_profile"]["show_purchased_filter"] = "";
$_MAG_DATA["get_profile"]["enable_connection_problem_indication"] = "1";
$_MAG_DATA["get_profile"]["invert_channel_switch_direction"] = "";
$_MAG_DATA["get_profile"]["enable_stream_error_logging"] = "";
$_MAG_DATA["get_profile"]["always_enabled_subtitles"] = "";
$_MAG_DATA["get_profile"]["enable_service_button"] = "";
$_MAG_DATA["get_profile"]["show_tv_channel_logo"] = "1";
$_MAG_DATA["get_profile"]["tv_archive_continued"] = "";
$_MAG_DATA["get_profile"]["show_tv_only_hd_filter_option"] = "";
$_MAG_DATA["get_profile"]["tv_playback_retry_limit"] = "3";
$_MAG_DATA["get_profile"]["fading_tv_retry_timeout"] = "1";
$_MAG_DATA["get_profile"]["epg_update_time_range"] = "3108";
$_MAG_DATA["get_profile"]["store_auth_data_on_stb"] = "";
$_MAG_DATA["get_profile"]["account_page_by_password"] = "";
$_MAG_DATA["get_profile"]["tester"] = "";
$_MAG_DATA["get_profile"]["show_channel_logo_in_preview"] = "";
$_MAG_DATA["get_profile"]["enable_stream_losses_logging"] = "";
$_MAG_DATA["get_profile"]["external_payment_page_url"] = "";
$_MAG_DATA["get_profile"]["max_local_recordings"] = "10";
$_MAG_DATA["gmode_720"][0] = "template/default/i_720/horoscope_menu_button_1_1_b.png";
$_MAG_DATA["gmode_720"][1] = "template/default/i_720/footer_menu_act.png";
$_MAG_DATA["gmode_720"][2] = "template/default/i_720/tv_table.png";
$_MAG_DATA["gmode_720"][3] = "template/default/i_720/dots.png";
$_MAG_DATA["gmode_720"][4] = "template/default/i_720/mb_table05.png";
$_MAG_DATA["gmode_720"][5] = "template/default/i_720/1.png";
$_MAG_DATA["gmode_720"][6] = "template/default/i_720/0.png";
$_MAG_DATA["gmode_720"][7] = "template/default/i_720/mb_table07.png";
$_MAG_DATA["gmode_720"][8] = "template/default/i_720/horoscope_menu_button_1_5_a.png";
$_MAG_DATA["gmode_720"][9] = "template/default/i_720/mm_ico_youtube.png";
$_MAG_DATA["gmode_720"][10] = "template/default/i_720/25alfa_20.png";
$_MAG_DATA["gmode_720"][11] = "template/default/i_720/6.png";
$_MAG_DATA["gmode_720"][12] = "template/default/i_720/osd_bg.png";
$_MAG_DATA["gmode_720"][13] = "template/default/i_720/_6_lightning.png";
$_MAG_DATA["gmode_720"][14] = "template/default/i_720/ico_issue.png";
$_MAG_DATA["gmode_720"][15] = "template/default/i_720/osd_btn.png";
$_MAG_DATA["gmode_720"][16] = "template/default/i_720/horoscope_menu_button_1_1_a.png";
$_MAG_DATA["gmode_720"][17] = "template/default/i_720/mm_ico_info.png";
$_MAG_DATA["gmode_720"][18] = "template/default/i_720/horoscope_menu_button_1_7_b.png";
$_MAG_DATA["gmode_720"][19] = "template/default/i_720/horoscope_menu_button_1_10_b.png";
$_MAG_DATA["gmode_720"][20] = "template/default/i_720/mm_vert_cell.png";
$_MAG_DATA["gmode_720"][21] = "template/default/i_720/mb_scroll.png";
$_MAG_DATA["gmode_720"][22] = "template/default/i_720/mb_table06.png";
$_MAG_DATA["gmode_720"][23] = "template/default/i_720/skip.png";
$_MAG_DATA["gmode_720"][24] = "template/default/i_720/mb_pass_input.png";
$_MAG_DATA["gmode_720"][25] = "template/default/i_720/mm_ico_account.png";
$_MAG_DATA["gmode_720"][26] = "template/default/i_720/mm_ico_tv.png";
$_MAG_DATA["gmode_720"][27] = "template/default/i_720/mb_table_act04.png";
$_MAG_DATA["gmode_720"][28] = "template/default/i_720/horoscope_menu_button_1_10_a.png";
$_MAG_DATA["gmode_720"][29] = "template/default/i_720/mb_table04.png";
$_MAG_DATA["gmode_720"][30] = "template/default/i_720/_3_pasmurno.png";
$_MAG_DATA["gmode_720"][31] = "template/default/i_720/deg.png";
$_MAG_DATA["gmode_720"][32] = "template/default/i_720/horoscope_menu_button_1_2_a.png";
$_MAG_DATA["gmode_720"][33] = "template/default/i_720/v_menu_1b.png";
$_MAG_DATA["gmode_720"][34] = "template/default/i_720/epg_red_mark.png";
$_MAG_DATA["gmode_720"][35] = "template/default/i_720/mb_prev_bg.png";
$_MAG_DATA["gmode_720"][36] = "template/default/i_720/aspect_bg.png";
$_MAG_DATA["gmode_720"][37] = "template/default/i_720/modal_bg.png";
$_MAG_DATA["gmode_720"][38] = "template/default/i_720/osd_line_pos.png";
$_MAG_DATA["gmode_720"][39] = "template/default/i_720/black85.png";
$_MAG_DATA["gmode_720"][40] = "template/default/i_720/input.png";
$_MAG_DATA["gmode_720"][41] = "template/default/i_720/input_episode_bg.png";
$_MAG_DATA["gmode_720"][42] = "template/default/i_720/mb_table_act05.png";
$_MAG_DATA["gmode_720"][43] = "template/default/i_720/_0_moon.png";
$_MAG_DATA["gmode_720"][44] = "template/default/i_720/_0_sun.png";
$_MAG_DATA["gmode_720"][45] = "template/default/i_720/ico_alert.png";
$_MAG_DATA["gmode_720"][46] = "template/default/i_720/ears.png";
$_MAG_DATA["gmode_720"][47] = "template/default/i_720/5.png";
$_MAG_DATA["gmode_720"][48] = "template/default/i_720/1x1.gif";
$_MAG_DATA["gmode_720"][49] = "template/default/i_720/footer_sidepanel_arr.png";
$_MAG_DATA["gmode_720"][50] = "template/default/i_720/horoscope_menu_button_1_9_b.png";
$_MAG_DATA["gmode_720"][51] = "template/default/i_720/mm_ico_internet.png";
$_MAG_DATA["gmode_720"][52] = "template/default/i_720/mm_hor_left.png";
$_MAG_DATA["gmode_720"][53] = "template/default/i_720/v_menu_5.png";
$_MAG_DATA["gmode_720"][54] = "template/default/i_720/ears_arrow_l.png";
$_MAG_DATA["gmode_720"][55] = "template/default/i_720/footer_sidepanel_line.png";
$_MAG_DATA["gmode_720"][56] = "template/default/i_720/horoscope_menu_button_1_8_a.png";
$_MAG_DATA["gmode_720"][57] = "template/default/i_720/_2_cloudy.png";
$_MAG_DATA["gmode_720"][58] = "template/default/i_720/input_episode.png";
$_MAG_DATA["gmode_720"][59] = "template/default/i_720/ico_error26.png";
$_MAG_DATA["gmode_720"][60] = "template/default/i_720/osd_rec.png";
$_MAG_DATA["gmode_720"][61] = "template/default/i_720/footer_sidepanel_l.png";
$_MAG_DATA["gmode_720"][62] = "template/default/i_720/mb_quality.png";
$_MAG_DATA["gmode_720"][63] = "template/default/i_720/footer_search.png";
$_MAG_DATA["gmode_720"][64] = "template/default/i_720/tv_table_arrows.png";
$_MAG_DATA["gmode_720"][65] = "template/default/i_720/ears_arrow_r.png";
$_MAG_DATA["gmode_720"][66] = "template/default/i_720/footer_bg.png";
$_MAG_DATA["gmode_720"][67] = "template/default/i_720/volume_off.png";
$_MAG_DATA["gmode_720"][68] = "template/default/i_720/_255_NA.png";
$_MAG_DATA["gmode_720"][69] = "template/default/i_720/7.png";
$_MAG_DATA["gmode_720"][70] = "template/default/i_720/mb_icon_rec.png";
$_MAG_DATA["gmode_720"][71] = "template/default/i_720/mb_icon_scrambled.png";
$_MAG_DATA["gmode_720"][72] = "template/default/i_720/arr_right.png";
$_MAG_DATA["gmode_720"][73] = "template/default/i_720/footer_sidepanel_act.png";
$_MAG_DATA["gmode_720"][74] = "template/default/i_720/mb_table01.png";
$_MAG_DATA["gmode_720"][75] = "template/default/i_720/tv_table_separator.png";
$_MAG_DATA["gmode_720"][76] = "template/default/i_720/mm_ico_android.png";
$_MAG_DATA["gmode_720"][77] = "template/default/i_720/mm_ico_ivi.png";
$_MAG_DATA["gmode_720"][78] = "template/default/i_720/mm_hor_bg1.png";
$_MAG_DATA["gmode_720"][79] = "template/default/i_720/mm_ico_usb.png";
$_MAG_DATA["gmode_720"][80] = "template/default/i_720/mm_ico_pomogator.png";
$_MAG_DATA["gmode_720"][81] = "template/default/i_720/mm_ico_zoomby.png";
$_MAG_DATA["gmode_720"][82] = "template/default/i_720/horoscope_menu_button_1_3_b.png";
$_MAG_DATA["gmode_720"][83] = "template/default/i_720/_1_sun_cl.png";
$_MAG_DATA["gmode_720"][84] = "template/default/i_720/mm_ico_tvzavr.png";
$_MAG_DATA["gmode_720"][85] = "template/default/i_720/2.png";
$_MAG_DATA["gmode_720"][86] = "template/default/i_720/epg_orange_mark.png";
$_MAG_DATA["gmode_720"][87] = "template/default/i_720/volume_bg.png";
$_MAG_DATA["gmode_720"][88] = "template/default/i_720/horoscope_menu_button_1_9_a.png";
$_MAG_DATA["gmode_720"][89] = "template/default/i_720/v_menu_3.png";
$_MAG_DATA["gmode_720"][90] = "template/default/i_720/horoscope_menu_button_1_6_b.png";
$_MAG_DATA["gmode_720"][91] = "template/default/i_720/input_act.png";
$_MAG_DATA["gmode_720"][92] = "template/default/i_720/_7_hail.png";
$_MAG_DATA["gmode_720"][93] = "template/default/i_720/mm_ico_setting.png";
$_MAG_DATA["gmode_720"][94] = "template/default/i_720/tv_table_focus.png";
$_MAG_DATA["gmode_720"][95] = "template/default/i_720/mb_context_bg.png";
$_MAG_DATA["gmode_720"][96] = "template/default/i_720/mb_filminfo_trans.png";
$_MAG_DATA["gmode_720"][97] = "template/default/i_720/horoscope_menu_button_1_12_b.png";
$_MAG_DATA["gmode_720"][98] = "template/default/i_720/mb_table_act02.png";
$_MAG_DATA["gmode_720"][99] = "template/default/i_720/mm_hor_right.png";
$_MAG_DATA["gmode_720"][100] = "template/default/i_720/epg_green_mark.png";
$_MAG_DATA["gmode_720"][101] = "template/default/i_720/v_menu_2b.png";
$_MAG_DATA["gmode_720"][102] = "template/default/i_720/_1_moon_cl.png";
$_MAG_DATA["gmode_720"][103] = "template/default/i_720/horoscope_menu_button_1_11_a.png";
$_MAG_DATA["gmode_720"][104] = "template/default/i_720/footer_sidepanel.png";
$_MAG_DATA["gmode_720"][105] = "template/default/i_720/v_menu_1a.png";
$_MAG_DATA["gmode_720"][106] = "template/default/i_720/hr_filminfo.png";
$_MAG_DATA["gmode_720"][107] = "template/default/i_720/horoscope_menu_button_1_5_b.png";
$_MAG_DATA["gmode_720"][108] = "template/default/i_720/horoscope_menu_button_1_2_b.png";
$_MAG_DATA["gmode_720"][109] = "template/default/i_720/mm_hor_bg3.png";
$_MAG_DATA["gmode_720"][110] = "template/default/i_720/horoscope_menu_button_1_6_a.png";
$_MAG_DATA["gmode_720"][111] = "template/default/i_720/mm_ico_ex.png";
$_MAG_DATA["gmode_720"][112] = "template/default/i_720/item_bg.png";
$_MAG_DATA["gmode_720"][113] = "template/default/i_720/footer_bg2.png";
$_MAG_DATA["gmode_720"][114] = "template/default/i_720/horoscope_menu_button_1_3_a.png";
$_MAG_DATA["gmode_720"][115] = "template/default/i_720/low_q.png";
$_MAG_DATA["gmode_720"][116] = "template/default/i_720/8.png";
$_MAG_DATA["gmode_720"][117] = "template/default/i_720/4.png";
$_MAG_DATA["gmode_720"][118] = "template/default/i_720/horoscope_menu_button_1_4_b.png";
$_MAG_DATA["gmode_720"][119] = "template/default/i_720/mm_ico_apps.png";
$_MAG_DATA["gmode_720"][120] = "template/default/i_720/mm_ico_megogo.png";
$_MAG_DATA["gmode_720"][121] = "template/default/i_720/footer_btn.png";
$_MAG_DATA["gmode_720"][122] = "template/default/i_720/mb_scroll_bg.png";
$_MAG_DATA["gmode_720"][123] = "template/default/i_720/bg.png";
$_MAG_DATA["gmode_720"][124] = "template/default/i_720/btn2.png";
$_MAG_DATA["gmode_720"][125] = "template/default/i_720/mb_context_borders.png";
$_MAG_DATA["gmode_720"][126] = "template/default/i_720/horoscope_menu_button_1_11_b.png";
$_MAG_DATA["gmode_720"][127] = "template/default/i_720/_10_heavy_snow.png";
$_MAG_DATA["gmode_720"][128] = "template/default/i_720/mb_icons.png";
$_MAG_DATA["gmode_720"][129] = "template/default/i_720/3.png";
$_MAG_DATA["gmode_720"][130] = "template/default/i_720/_5_rain.png";
$_MAG_DATA["gmode_720"][131] = "template/default/i_720/mb_table_act06.png";
$_MAG_DATA["gmode_720"][132] = "template/default/i_720/mm_ico_dm.png";
$_MAG_DATA["gmode_720"][133] = "template/default/i_720/volume_bar.png";
$_MAG_DATA["gmode_720"][134] = "template/default/i_720/footer_sidepanel_r.png";
$_MAG_DATA["gmode_720"][135] = "template/default/i_720/ico_confirm.png";
$_MAG_DATA["gmode_720"][136] = "template/default/i_720/mb_table_act01.png";
$_MAG_DATA["gmode_720"][137] = "template/default/i_720/footer_menu.png";
$_MAG_DATA["gmode_720"][138] = "template/default/i_720/ico_info.png";
$_MAG_DATA["gmode_720"][139] = "template/default/i_720/minus.png";
$_MAG_DATA["gmode_720"][140] = "template/default/i_720/mm_ico_karaoke.png";
$_MAG_DATA["gmode_720"][141] = "template/default/i_720/v_menu_2a.png";
$_MAG_DATA["gmode_720"][142] = "template/default/i_720/_9_snow.png";
$_MAG_DATA["gmode_720"][143] = "template/default/i_720/mb_table_act03.png";
$_MAG_DATA["gmode_720"][144] = "template/default/i_720/mm_ico_video.png";
$_MAG_DATA["gmode_720"][145] = "template/default/i_720/footer_search_act2.png";
$_MAG_DATA["gmode_720"][146] = "template/default/i_720/input_channel.png";
$_MAG_DATA["gmode_720"][147] = "template/default/i_720/horoscope_menu_button_1_4_a.png";
$_MAG_DATA["gmode_720"][148] = "template/default/i_720/osd_time.png";
$_MAG_DATA["gmode_720"][149] = "template/default/i_720/tv_prev_bg.png";
$_MAG_DATA["gmode_720"][150] = "template/default/i_720/osd_line.png";
$_MAG_DATA["gmode_720"][151] = "template/default/i_720/horoscope_menu_button_1_7_a.png";
$_MAG_DATA["gmode_720"][152] = "template/default/i_720/9.png";
$_MAG_DATA["gmode_720"][153] = "template/default/i_720/mb_table03.png";
$_MAG_DATA["gmode_720"][154] = "template/default/i_720/pause_btn.png";
$_MAG_DATA["gmode_720"][155] = "template/default/i_720/input_channel_bg.png";
$_MAG_DATA["gmode_720"][156] = "template/default/i_720/mb_pass_bg.png";
$_MAG_DATA["gmode_720"][157] = "template/default/i_720/mm_hor_bg2.png";
$_MAG_DATA["gmode_720"][158] = "template/default/i_720/loading.png";
$_MAG_DATA["gmode_720"][159] = "template/default/i_720/_4_short_rain.png";
$_MAG_DATA["gmode_720"][160] = "template/default/i_720/v_menu_4.png";
$_MAG_DATA["gmode_720"][161] = "template/default/i_720/arr_left.png";
$_MAG_DATA["gmode_720"][162] = "template/default/i_720/horoscope_menu_button_1_8_b.png";
$_MAG_DATA["gmode_720"][163] = "template/default/i_720/mb_table02.png";
$_MAG_DATA["gmode_720"][164] = "template/default/i_720/bg2.png";
$_MAG_DATA["gmode_720"][165] = "template/default/i_720/mm_ico_radio.png";
$_MAG_DATA["gmode_720"][166] = "template/default/i_720/mm_ico_vidimax.png";
$_MAG_DATA["gmode_720"][167] = "template/default/i_720/mb_player.png";
$_MAG_DATA["gmode_720"][168] = "template/default/i_720/_8_rain_swon.png";
$_MAG_DATA["gmode_720"][169] = "template/default/i_720/loading_bg.gif";
$_MAG_DATA["gmode_720"][170] = "template/default/i_720/plus.png";
$_MAG_DATA["gmode_720"][171] = "template/default/i_720/footer_search_act.png";
$_MAG_DATA["gmode_720"][172] = "template/default/i_720/vol_1.png";
$_MAG_DATA["gmode_720"][173] = "template/default/i_720/mm_ico_oll.png";
$_MAG_DATA["gmode_720"][174] = "template/default/i_720/horoscope_menu_button_1_12_a.png";
$_MAG_DATA["gmode_480"][0] = "template/default/i_480/horoscope_menu_button_1_1_b.png";
$_MAG_DATA["gmode_480"][1] = "template/default/i_480/footer_menu_act.png";
$_MAG_DATA["gmode_480"][2] = "template/default/i_480/tv_table.png";
$_MAG_DATA["gmode_480"][3] = "template/default/i_480/dots.png";
$_MAG_DATA["gmode_480"][4] = "template/default/i_480/ears2.png";
$_MAG_DATA["gmode_480"][5] = "template/default/i_480/1.png";
$_MAG_DATA["gmode_480"][6] = "template/default/i_480/0.png";
$_MAG_DATA["gmode_480"][7] = "template/default/i_480/w_snow.png";
$_MAG_DATA["gmode_480"][8] = "template/default/i_480/horoscope_menu_button_1_5_a.png";
$_MAG_DATA["gmode_480"][9] = "template/default/i_480/mm_ico_youtube.png";
$_MAG_DATA["gmode_480"][10] = "template/default/i_480/25alfa_20.png";
$_MAG_DATA["gmode_480"][11] = "template/default/i_480/6.png";
$_MAG_DATA["gmode_480"][12] = "template/default/i_480/osd_bg.png";
$_MAG_DATA["gmode_480"][13] = "template/default/i_480/_6_lightning.png";
$_MAG_DATA["gmode_480"][14] = "template/default/i_480/ico_issue.png";
$_MAG_DATA["gmode_480"][15] = "template/default/i_480/osd_btn.png";
$_MAG_DATA["gmode_480"][16] = "template/default/i_480/horoscope_menu_button_1_1_a.png";
$_MAG_DATA["gmode_480"][17] = "template/default/i_480/mm_ico_info.png";
$_MAG_DATA["gmode_480"][18] = "template/default/i_480/horoscope_menu_button_1_7_b.png";
$_MAG_DATA["gmode_480"][19] = "template/default/i_480/horoscope_menu_button_1_10_b.png";
$_MAG_DATA["gmode_480"][20] = "template/default/i_480/mm_vert_cell.png";
$_MAG_DATA["gmode_480"][21] = "template/default/i_480/mb_scroll.png";
$_MAG_DATA["gmode_480"][22] = "template/default/i_480/skip.png";
$_MAG_DATA["gmode_480"][23] = "template/default/i_480/mb_pass_input.png";
$_MAG_DATA["gmode_480"][24] = "template/default/i_480/mm_ico_account.png";
$_MAG_DATA["gmode_480"][25] = "template/default/i_480/mm_ico_tv.png";
$_MAG_DATA["gmode_480"][26] = "template/default/i_480/horoscope_menu_button_1_10_a.png";
$_MAG_DATA["gmode_480"][27] = "template/default/i_480/w_thunderstorm.png";
$_MAG_DATA["gmode_480"][28] = "template/default/i_480/w_moon.png";
$_MAG_DATA["gmode_480"][29] = "template/default/i_480/_3_pasmurno.png";
$_MAG_DATA["gmode_480"][30] = "template/default/i_480/deg.png";
$_MAG_DATA["gmode_480"][31] = "template/default/i_480/horoscope_menu_button_1_2_a.png";
$_MAG_DATA["gmode_480"][32] = "template/default/i_480/v_menu_1b.png";
$_MAG_DATA["gmode_480"][33] = "template/default/i_480/epg_red_mark.png";
$_MAG_DATA["gmode_480"][34] = "template/default/i_480/weather.png";
$_MAG_DATA["gmode_480"][35] = "template/default/i_480/mb_prev_bg.png";
$_MAG_DATA["gmode_480"][36] = "template/default/i_480/aspect_bg.png";
$_MAG_DATA["gmode_480"][37] = "template/default/i_480/modal_bg.png";
$_MAG_DATA["gmode_480"][38] = "template/default/i_480/osd_line_pos.png";
$_MAG_DATA["gmode_480"][39] = "template/default/i_480/mm_vert_border.png";
$_MAG_DATA["gmode_480"][40] = "template/default/i_480/black85.png";
$_MAG_DATA["gmode_480"][41] = "template/default/i_480/input.png";
$_MAG_DATA["gmode_480"][42] = "template/default/i_480/input_episode_bg.png";
$_MAG_DATA["gmode_480"][43] = "template/default/i_480/w_cloud_big.png";
$_MAG_DATA["gmode_480"][44] = "template/default/i_480/_0_moon.png";
$_MAG_DATA["gmode_480"][45] = "template/default/i_480/_0_sun.png";
$_MAG_DATA["gmode_480"][46] = "template/default/i_480/ico_alert.png";
$_MAG_DATA["gmode_480"][47] = "template/default/i_480/ears.png";
$_MAG_DATA["gmode_480"][48] = "template/default/i_480/5.png";
$_MAG_DATA["gmode_480"][49] = "template/default/i_480/1x1.gif";
$_MAG_DATA["gmode_480"][50] = "template/default/i_480/footer_sidepanel_arr.png";
$_MAG_DATA["gmode_480"][51] = "template/default/i_480/horoscope_menu_button_1_9_b.png";
$_MAG_DATA["gmode_480"][52] = "template/default/i_480/menu_item_img_1.png";
$_MAG_DATA["gmode_480"][53] = "template/default/i_480/w_empty.png";
$_MAG_DATA["gmode_480"][54] = "template/default/i_480/mm_ico_internet.png";
$_MAG_DATA["gmode_480"][55] = "template/default/i_480/mm_hor_left.png";
$_MAG_DATA["gmode_480"][56] = "template/default/i_480/v_menu_5.png";
$_MAG_DATA["gmode_480"][57] = "template/default/i_480/ears_arrow_l.png";
$_MAG_DATA["gmode_480"][58] = "template/default/i_480/footer_sidepanel_line.png";
$_MAG_DATA["gmode_480"][59] = "template/default/i_480/horoscope_menu_button_1_8_a.png";
$_MAG_DATA["gmode_480"][60] = "template/default/i_480/_2_cloudy.png";
$_MAG_DATA["gmode_480"][61] = "template/default/i_480/input_episode.png";
$_MAG_DATA["gmode_480"][62] = "template/default/i_480/ico_error26.png";
$_MAG_DATA["gmode_480"][63] = "template/default/i_480/mb_table.png";
$_MAG_DATA["gmode_480"][64] = "template/default/i_480/osd_rec.png";
$_MAG_DATA["gmode_480"][65] = "template/default/i_480/footer_sidepanel_l.png";
$_MAG_DATA["gmode_480"][66] = "template/default/i_480/mb_quality.png";
$_MAG_DATA["gmode_480"][67] = "template/default/i_480/footer_search.png";
$_MAG_DATA["gmode_480"][68] = "template/default/i_480/tv_table_arrows.png";
$_MAG_DATA["gmode_480"][69] = "template/default/i_480/ears_arrow_r.png";
$_MAG_DATA["gmode_480"][70] = "template/default/i_480/footer_bg.png";
$_MAG_DATA["gmode_480"][71] = "template/default/i_480/w_cloud_black.png";
$_MAG_DATA["gmode_480"][72] = "template/default/i_480/volume_off.png";
$_MAG_DATA["gmode_480"][73] = "template/default/i_480/_255_NA.png";
$_MAG_DATA["gmode_480"][74] = "template/default/i_480/7.png";
$_MAG_DATA["gmode_480"][75] = "template/default/i_480/mb_icon_rec.png";
$_MAG_DATA["gmode_480"][76] = "template/default/i_480/mb_icon_scrambled.png";
$_MAG_DATA["gmode_480"][77] = "template/default/i_480/arr_right.png";
$_MAG_DATA["gmode_480"][78] = "template/default/i_480/footer_sidepanel_act.png";
$_MAG_DATA["gmode_480"][79] = "template/default/i_480/w_rain_strong.png";
$_MAG_DATA["gmode_480"][80] = "template/default/i_480/tv_table_separator.png";
$_MAG_DATA["gmode_480"][81] = "template/default/i_480/mm_ico_ivi.png";
$_MAG_DATA["gmode_480"][82] = "template/default/i_480/mm_hor_bg1.png";
$_MAG_DATA["gmode_480"][83] = "template/default/i_480/mm_ico_usb.png";
$_MAG_DATA["gmode_480"][84] = "template/default/i_480/vol_2.png";
$_MAG_DATA["gmode_480"][85] = "template/default/i_480/mm_ico_pomogator.png";
$_MAG_DATA["gmode_480"][86] = "template/default/i_480/mm_ico_zoomby.png";
$_MAG_DATA["gmode_480"][87] = "template/default/i_480/horoscope_menu_button_1_3_b.png";
$_MAG_DATA["gmode_480"][88] = "template/default/i_480/_1_sun_cl.png";
$_MAG_DATA["gmode_480"][89] = "template/default/i_480/mm_ico_tvzavr.png";
$_MAG_DATA["gmode_480"][90] = "template/default/i_480/2.png";
$_MAG_DATA["gmode_480"][91] = "template/default/i_480/epg_orange_mark.png";
$_MAG_DATA["gmode_480"][92] = "template/default/i_480/volume_bg.png";
$_MAG_DATA["gmode_480"][93] = "template/default/i_480/horoscope_menu_button_1_9_a.png";
$_MAG_DATA["gmode_480"][94] = "template/default/i_480/v_menu_3.png";
$_MAG_DATA["gmode_480"][95] = "template/default/i_480/horoscope_menu_button_1_6_b.png";
$_MAG_DATA["gmode_480"][96] = "template/default/i_480/input_act.png";
$_MAG_DATA["gmode_480"][97] = "template/default/i_480/mb_context_btn.png";
$_MAG_DATA["gmode_480"][98] = "template/default/i_480/_7_hail.png";
$_MAG_DATA["gmode_480"][99] = "template/default/i_480/mm_ico_setting.png";
$_MAG_DATA["gmode_480"][100] = "template/default/i_480/tv_table_focus.png";
$_MAG_DATA["gmode_480"][101] = "template/default/i_480/mb_context_bg.png";
$_MAG_DATA["gmode_480"][102] = "template/default/i_480/mb_filminfo_trans.png";
$_MAG_DATA["gmode_480"][103] = "template/default/i_480/mb_icons2.png";
$_MAG_DATA["gmode_480"][104] = "template/default/i_480/mm_menu_vert.png";
$_MAG_DATA["gmode_480"][105] = "template/default/i_480/horoscope_menu_button_1_12_b.png";
$_MAG_DATA["gmode_480"][106] = "template/default/i_480/mm_hor_right.png";
$_MAG_DATA["gmode_480"][107] = "template/default/i_480/epg_green_mark.png";
$_MAG_DATA["gmode_480"][108] = "template/default/i_480/w_rain.png";
$_MAG_DATA["gmode_480"][109] = "template/default/i_480/v_menu_2b.png";
$_MAG_DATA["gmode_480"][110] = "template/default/i_480/_1_moon_cl.png";
$_MAG_DATA["gmode_480"][111] = "template/default/i_480/horoscope_menu_button_1_11_a.png";
$_MAG_DATA["gmode_480"][112] = "template/default/i_480/footer_sidepanel.png";
$_MAG_DATA["gmode_480"][113] = "template/default/i_480/v_menu_1a.png";
$_MAG_DATA["gmode_480"][114] = "template/default/i_480/hr_filminfo.png";
$_MAG_DATA["gmode_480"][115] = "template/default/i_480/horoscope_menu_button_1_5_b.png";
$_MAG_DATA["gmode_480"][116] = "template/default/i_480/horoscope_menu_button_1_2_b.png";
$_MAG_DATA["gmode_480"][117] = "template/default/i_480/mm_hor_bg3.png";
$_MAG_DATA["gmode_480"][118] = "template/default/i_480/horoscope_menu_button_1_6_a.png";
$_MAG_DATA["gmode_480"][119] = "template/default/i_480/mm_ico_ex.png";
$_MAG_DATA["gmode_480"][120] = "template/default/i_480/item_bg.png";
$_MAG_DATA["gmode_480"][121] = "template/default/i_480/footer_bg2.png";
$_MAG_DATA["gmode_480"][122] = "template/default/i_480/horoscope_menu_button_1_3_a.png";
$_MAG_DATA["gmode_480"][123] = "template/default/i_480/low_q.png";
$_MAG_DATA["gmode_480"][124] = "template/default/i_480/8.png";
$_MAG_DATA["gmode_480"][125] = "template/default/i_480/4.png";
$_MAG_DATA["gmode_480"][126] = "template/default/i_480/horoscope_menu_button_1_4_b.png";
$_MAG_DATA["gmode_480"][127] = "template/default/i_480/mm_menu_hor.png";
$_MAG_DATA["gmode_480"][128] = "template/default/i_480/mm_ico_megogo.png";
$_MAG_DATA["gmode_480"][129] = "template/default/i_480/footer_btn.png";
$_MAG_DATA["gmode_480"][130] = "template/default/i_480/mb_scroll_bg.png";
$_MAG_DATA["gmode_480"][131] = "template/default/i_480/bg.png";
$_MAG_DATA["gmode_480"][132] = "template/default/i_480/w_snow_strong.png";
$_MAG_DATA["gmode_480"][133] = "template/default/i_480/btn2.png";
$_MAG_DATA["gmode_480"][134] = "template/default/i_480/mb_table_act.png";
$_MAG_DATA["gmode_480"][135] = "template/default/i_480/prev_img.jpg";
$_MAG_DATA["gmode_480"][136] = "template/default/i_480/mb_context_borders.png";
$_MAG_DATA["gmode_480"][137] = "template/default/i_480/horoscope_menu_button_1_11_b.png";
$_MAG_DATA["gmode_480"][138] = "template/default/i_480/w_sun.png";
$_MAG_DATA["gmode_480"][139] = "template/default/i_480/_10_heavy_snow.png";
$_MAG_DATA["gmode_480"][140] = "template/default/i_480/mb_icons.png";
$_MAG_DATA["gmode_480"][141] = "template/default/i_480/3.png";
$_MAG_DATA["gmode_480"][142] = "template/default/i_480/_5_rain.png";
$_MAG_DATA["gmode_480"][143] = "template/default/i_480/mb_table_act06.png";
$_MAG_DATA["gmode_480"][144] = "template/default/i_480/mm_ico_dm.png";
$_MAG_DATA["gmode_480"][145] = "template/default/i_480/volume_bar.png";
$_MAG_DATA["gmode_480"][146] = "template/default/i_480/footer_sidepanel_r.png";
$_MAG_DATA["gmode_480"][147] = "template/default/i_480/ico_confirm.png";
$_MAG_DATA["gmode_480"][148] = "template/default/i_480/footer_menu.png";
$_MAG_DATA["gmode_480"][149] = "template/default/i_480/ico_info.png";
$_MAG_DATA["gmode_480"][150] = "template/default/i_480/minus.png";
$_MAG_DATA["gmode_480"][151] = "template/default/i_480/mm_ico_karaoke.png";
$_MAG_DATA["gmode_480"][152] = "template/default/i_480/v_menu_2a.png";
$_MAG_DATA["gmode_480"][153] = "template/default/i_480/_9_snow.png";
$_MAG_DATA["gmode_480"][154] = "template/default/i_480/mm_ico_video.png";
$_MAG_DATA["gmode_480"][155] = "template/default/i_480/footer_search_act2.png";
$_MAG_DATA["gmode_480"][156] = "template/default/i_480/input_channel.png";
$_MAG_DATA["gmode_480"][157] = "template/default/i_480/horoscope_menu_button_1_4_a.png";
$_MAG_DATA["gmode_480"][158] = "template/default/i_480/w_cloud_small.png";
$_MAG_DATA["gmode_480"][159] = "template/default/i_480/osd_time.png";
$_MAG_DATA["gmode_480"][160] = "template/default/i_480/tv_prev_bg.png";
$_MAG_DATA["gmode_480"][161] = "template/default/i_480/osd_line.png";
$_MAG_DATA["gmode_480"][162] = "template/default/i_480/footer_search_act_.png";
$_MAG_DATA["gmode_480"][163] = "template/default/i_480/horoscope_menu_button_1_7_a.png";
$_MAG_DATA["gmode_480"][164] = "template/default/i_480/9.png";
$_MAG_DATA["gmode_480"][165] = "template/default/i_480/pause_btn.png";
$_MAG_DATA["gmode_480"][166] = "template/default/i_480/input_channel_bg.png";
$_MAG_DATA["gmode_480"][167] = "template/default/i_480/mm_vert_trans.png";
$_MAG_DATA["gmode_480"][168] = "template/default/i_480/mb_pass_bg.png";
$_MAG_DATA["gmode_480"][169] = "template/default/i_480/mm_hor_bg2.png";
$_MAG_DATA["gmode_480"][170] = "template/default/i_480/loading.png";
$_MAG_DATA["gmode_480"][171] = "template/default/i_480/_4_short_rain.png";
$_MAG_DATA["gmode_480"][172] = "template/default/i_480/v_menu_4.png";
$_MAG_DATA["gmode_480"][173] = "template/default/i_480/arr_left.png";
$_MAG_DATA["gmode_480"][174] = "template/default/i_480/horoscope_menu_button_1_8_b.png";
$_MAG_DATA["gmode_480"][175] = "template/default/i_480/bg2.png";
$_MAG_DATA["gmode_480"][176] = "template/default/i_480/mm_ico_radio.png";
$_MAG_DATA["gmode_480"][177] = "template/default/i_480/mm_ico_vidimax.png";
$_MAG_DATA["gmode_480"][178] = "template/default/i_480/mb_player.png";
$_MAG_DATA["gmode_480"][179] = "template/default/i_480/_8_rain_swon.png";
$_MAG_DATA["gmode_480"][180] = "template/default/i_480/loading_bg.gif";
$_MAG_DATA["gmode_480"][181] = "template/default/i_480/plus.png";
$_MAG_DATA["gmode_480"][182] = "template/default/i_480/footer_search_act.png";
$_MAG_DATA["gmode_480"][183] = "template/default/i_480/vol_1.png";
$_MAG_DATA["gmode_480"][184] = "template/default/i_480/mm_ico_oll.png";
$_MAG_DATA["gmode_480"][185] = "template/default/i_480/horoscope_menu_button_1_12_a.png";
$_MAG_DATA["gmode_default"][0] = "template/default/i/horoscope_menu_button_1_1_b.png";
$_MAG_DATA["gmode_default"][1] = "template/default/i/footer_menu_act.png";
$_MAG_DATA["gmode_default"][2] = "template/default/i/tv_table.png";
$_MAG_DATA["gmode_default"][3] = "template/default/i/mb_table05.png";
$_MAG_DATA["gmode_default"][4] = "template/default/i/mb_table07.png";
$_MAG_DATA["gmode_default"][5] = "template/default/i/w_snow.png";
$_MAG_DATA["gmode_default"][6] = "template/default/i/horoscope_menu_button_1_5_a.png";
$_MAG_DATA["gmode_default"][7] = "template/default/i/mm_ico_youtube.png";
$_MAG_DATA["gmode_default"][8] = "template/default/i/25alfa_20.png";
$_MAG_DATA["gmode_default"][9] = "template/default/i/osd_bg.png";
$_MAG_DATA["gmode_default"][10] = "template/default/i/_6_lightning.png";
$_MAG_DATA["gmode_default"][11] = "template/default/i/horoscope_menu_button_1_1_a.png";
$_MAG_DATA["gmode_default"][12] = "template/default/i/mm_ico_info.png";
$_MAG_DATA["gmode_default"][13] = "template/default/i/horoscope_menu_button_1_7_b.png";
$_MAG_DATA["gmode_default"][14] = "template/default/i/horoscope_menu_button_1_10_b.png";
$_MAG_DATA["gmode_default"][15] = "template/default/i/mm_vert_cell.png";
$_MAG_DATA["gmode_default"][16] = "template/default/i/mb_scroll.png";
$_MAG_DATA["gmode_default"][17] = "template/default/i/mb_table06.png";
$_MAG_DATA["gmode_default"][18] = "template/default/i/skip.png";
$_MAG_DATA["gmode_default"][19] = "template/default/i/combobox_act.png";
$_MAG_DATA["gmode_default"][20] = "template/default/i/mb_pass_input.png";
$_MAG_DATA["gmode_default"][21] = "template/default/i/mm_ico_account.png";
$_MAG_DATA["gmode_default"][22] = "template/default/i/mm_ico_tv.png";
$_MAG_DATA["gmode_default"][23] = "template/default/i/mb_table_act04.png";
$_MAG_DATA["gmode_default"][24] = "template/default/i/horoscope_menu_button_1_10_a.png";
$_MAG_DATA["gmode_default"][25] = "template/default/i/w_thunderstorm.png";
$_MAG_DATA["gmode_default"][26] = "template/default/i/mb_table04.png";
$_MAG_DATA["gmode_default"][27] = "template/default/i/w_moon.png";
$_MAG_DATA["gmode_default"][28] = "template/default/i/_3_pasmurno.png";
$_MAG_DATA["gmode_default"][29] = "template/default/i/horoscope_menu_button_1_2_a.png";
$_MAG_DATA["gmode_default"][30] = "template/default/i/v_menu_1b.png";
$_MAG_DATA["gmode_default"][31] = "template/default/i/epg_red_mark.png";
$_MAG_DATA["gmode_default"][32] = "template/default/i/weather.png";
$_MAG_DATA["gmode_default"][33] = "template/default/i/mb_prev_bg.png";
$_MAG_DATA["gmode_default"][34] = "template/default/i/aspect_bg.png";
$_MAG_DATA["gmode_default"][35] = "template/default/i/modal_bg.png";
$_MAG_DATA["gmode_default"][36] = "template/default/i/osd_line_pos.png";
$_MAG_DATA["gmode_default"][37] = "template/default/i/mm_vert_border.png";
$_MAG_DATA["gmode_default"][38] = "template/default/i/black85.png";
$_MAG_DATA["gmode_default"][39] = "template/default/i/input.png";
$_MAG_DATA["gmode_default"][40] = "template/default/i/input_episode_bg.png";
$_MAG_DATA["gmode_default"][41] = "template/default/i/w_cloud_big.png";
$_MAG_DATA["gmode_default"][42] = "template/default/i/mb_table_act05.png";
$_MAG_DATA["gmode_default"][43] = "template/default/i/_0_moon.png";
$_MAG_DATA["gmode_default"][44] = "template/default/i/_0_sun.png";
$_MAG_DATA["gmode_default"][45] = "template/default/i/ico_alert.png";
$_MAG_DATA["gmode_default"][46] = "template/default/i/ears.png";
$_MAG_DATA["gmode_default"][47] = "template/default/i/footer_sidepanel_arr.png";
$_MAG_DATA["gmode_default"][48] = "template/default/i/horoscope_menu_button_1_9_b.png";
$_MAG_DATA["gmode_default"][49] = "template/default/i/w_empty.png";
$_MAG_DATA["gmode_default"][50] = "template/default/i/mm_ico_internet.png";
$_MAG_DATA["gmode_default"][51] = "template/default/i/mm_hor_left.png";
$_MAG_DATA["gmode_default"][52] = "template/default/i/v_menu_5.png";
$_MAG_DATA["gmode_default"][53] = "template/default/i/ears_arrow_l.png";
$_MAG_DATA["gmode_default"][54] = "template/default/i/footer_sidepanel_line.png";
$_MAG_DATA["gmode_default"][55] = "template/default/i/horoscope_menu_button_1_8_a.png";
$_MAG_DATA["gmode_default"][56] = "template/default/i/_2_cloudy.png";
$_MAG_DATA["gmode_default"][57] = "template/default/i/ico_error26.png";
$_MAG_DATA["gmode_default"][58] = "template/default/i/osd_rec.png";
$_MAG_DATA["gmode_default"][59] = "template/default/i/footer_sidepanel_l.png";
$_MAG_DATA["gmode_default"][60] = "template/default/i/mb_quality.png";
$_MAG_DATA["gmode_default"][61] = "template/default/i/footer_search.png";
$_MAG_DATA["gmode_default"][62] = "template/default/i/tv_table_arrows.png";
$_MAG_DATA["gmode_default"][63] = "template/default/i/ears_arrow_r.png";
$_MAG_DATA["gmode_default"][64] = "template/default/i/footer_bg.png";
$_MAG_DATA["gmode_default"][65] = "template/default/i/combobox.png";
$_MAG_DATA["gmode_default"][66] = "template/default/i/w_cloud_black.png";
$_MAG_DATA["gmode_default"][67] = "template/default/i/volume_off.png";
$_MAG_DATA["gmode_default"][68] = "template/default/i/_255_NA.png";
$_MAG_DATA["gmode_default"][69] = "template/default/i/mb_icon_rec.png";
$_MAG_DATA["gmode_default"][70] = "template/default/i/mb_icon_scrambled.png";
$_MAG_DATA["gmode_default"][71] = "template/default/i/arr_right.png";
$_MAG_DATA["gmode_default"][72] = "template/default/i/footer_sidepanel_act.png";
$_MAG_DATA["gmode_default"][73] = "template/default/i/mb_table01.png";
$_MAG_DATA["gmode_default"][74] = "template/default/i/w_rain_strong.png";
$_MAG_DATA["gmode_default"][75] = "template/default/i/tv_table_separator.png";
$_MAG_DATA["gmode_default"][76] = "template/default/i/mm_ico_ivi.png";
$_MAG_DATA["gmode_default"][77] = "template/default/i/mm_hor_bg1.png";
$_MAG_DATA["gmode_default"][78] = "template/default/i/mm_ico_usb.png";
$_MAG_DATA["gmode_default"][79] = "template/default/i/mm_ico_pomogator.png";
$_MAG_DATA["gmode_default"][80] = "template/default/i/mm_ico_zoomby.png";
$_MAG_DATA["gmode_default"][81] = "template/default/i/horoscope_menu_button_1_3_b.png";
$_MAG_DATA["gmode_default"][82] = "template/default/i/_1_sun_cl.png";
$_MAG_DATA["gmode_default"][83] = "template/default/i/mm_ico_tvzavr.png";
$_MAG_DATA["gmode_default"][84] = "template/default/i/epg_orange_mark.png";
$_MAG_DATA["gmode_default"][85] = "template/default/i/volume_bg.png";
$_MAG_DATA["gmode_default"][86] = "template/default/i/horoscope_menu_button_1_9_a.png";
$_MAG_DATA["gmode_default"][87] = "template/default/i/v_menu_3.png";
$_MAG_DATA["gmode_default"][88] = "template/default/i/horoscope_menu_button_1_6_b.png";
$_MAG_DATA["gmode_default"][89] = "template/default/i/input_act.png";
$_MAG_DATA["gmode_default"][90] = "template/default/i/_7_hail.png";
$_MAG_DATA["gmode_default"][91] = "template/default/i/mm_ico_setting.png";
$_MAG_DATA["gmode_default"][92] = "template/default/i/tv_table_focus.png";
$_MAG_DATA["gmode_default"][93] = "template/default/i/mb_context_bg.png";
$_MAG_DATA["gmode_default"][94] = "template/default/i/mb_filminfo_trans.png";
$_MAG_DATA["gmode_default"][95] = "template/default/i/mm_menu_vert.png";
$_MAG_DATA["gmode_default"][96] = "template/default/i/horoscope_menu_button_1_12_b.png";
$_MAG_DATA["gmode_default"][97] = "template/default/i/mb_table_act02.png";
$_MAG_DATA["gmode_default"][98] = "template/default/i/mm_hor_right.png";
$_MAG_DATA["gmode_default"][99] = "template/default/i/epg_green_mark.png";
$_MAG_DATA["gmode_default"][100] = "template/default/i/w_rain.png";
$_MAG_DATA["gmode_default"][101] = "template/default/i/v_menu_2b.png";
$_MAG_DATA["gmode_default"][102] = "template/default/i/_1_moon_cl.png";
$_MAG_DATA["gmode_default"][103] = "template/default/i/horoscope_menu_button_1_11_a.png";
$_MAG_DATA["gmode_default"][104] = "template/default/i/footer_sidepanel.png";
$_MAG_DATA["gmode_default"][105] = "template/default/i/v_menu_1a.png";
$_MAG_DATA["gmode_default"][106] = "template/default/i/hr_filminfo.png";
$_MAG_DATA["gmode_default"][107] = "template/default/i/horoscope_menu_button_1_5_b.png";
$_MAG_DATA["gmode_default"][108] = "template/default/i/horoscope_menu_button_1_2_b.png";
$_MAG_DATA["gmode_default"][109] = "template/default/i/mm_hor_bg3.png";
$_MAG_DATA["gmode_default"][110] = "template/default/i/horoscope_menu_button_1_6_a.png";
$_MAG_DATA["gmode_default"][111] = "template/default/i/mm_ico_ex.png";
$_MAG_DATA["gmode_default"][112] = "template/default/i/item_bg.png";
$_MAG_DATA["gmode_default"][113] = "template/default/i/footer_bg2.png";
$_MAG_DATA["gmode_default"][114] = "template/default/i/horoscope_menu_button_1_3_a.png";
$_MAG_DATA["gmode_default"][115] = "template/default/i/low_q.png";
$_MAG_DATA["gmode_default"][116] = "template/default/i/horoscope_menu_button_1_4_b.png";
$_MAG_DATA["gmode_default"][117] = "template/default/i/mm_menu_hor.png";
$_MAG_DATA["gmode_default"][118] = "template/default/i/mm_ico_megogo.png";
$_MAG_DATA["gmode_default"][119] = "template/default/i/footer_btn.png";
$_MAG_DATA["gmode_default"][120] = "template/default/i/mb_scroll_bg.png";
$_MAG_DATA["gmode_default"][121] = "template/default/i/bg.png";
$_MAG_DATA["gmode_default"][122] = "template/default/i/w_snow_strong.png";
$_MAG_DATA["gmode_default"][123] = "template/default/i/btn2.png";
$_MAG_DATA["gmode_default"][124] = "template/default/i/mb_context_borders.png";
$_MAG_DATA["gmode_default"][125] = "template/default/i/horoscope_menu_button_1_11_b.png";
$_MAG_DATA["gmode_default"][126] = "template/default/i/w_sun.png";
$_MAG_DATA["gmode_default"][127] = "template/default/i/_10_heavy_snow.png";
$_MAG_DATA["gmode_default"][128] = "template/default/i/mb_icons.png";
$_MAG_DATA["gmode_default"][129] = "template/default/i/_5_rain.png";
$_MAG_DATA["gmode_default"][130] = "template/default/i/mb_table_act06.png";
$_MAG_DATA["gmode_default"][131] = "template/default/i/mm_ico_dm.png";
$_MAG_DATA["gmode_default"][132] = "template/default/i/volume_bar.png";
$_MAG_DATA["gmode_default"][133] = "template/default/i/footer_sidepanel_r.png";
$_MAG_DATA["gmode_default"][134] = "template/default/i/ico_confirm.png";
$_MAG_DATA["gmode_default"][135] = "template/default/i/mb_table_act01.png";
$_MAG_DATA["gmode_default"][136] = "template/default/i/footer_menu.png";
$_MAG_DATA["gmode_default"][137] = "template/default/i/ico_info.png";
$_MAG_DATA["gmode_default"][138] = "template/default/i/mm_ico_karaoke.png";
$_MAG_DATA["gmode_default"][139] = "template/default/i/v_menu_2a.png";
$_MAG_DATA["gmode_default"][140] = "template/default/i/_9_snow.png";
$_MAG_DATA["gmode_default"][141] = "template/default/i/mb_table_act03.png";
$_MAG_DATA["gmode_default"][142] = "template/default/i/mm_ico_video.png";
$_MAG_DATA["gmode_default"][143] = "template/default/i/footer_search_act2.png";
$_MAG_DATA["gmode_default"][144] = "template/default/i/input_channel.png";
$_MAG_DATA["gmode_default"][145] = "template/default/i/horoscope_menu_button_1_4_a.png";
$_MAG_DATA["gmode_default"][146] = "template/default/i/w_cloud_small.png";
$_MAG_DATA["gmode_default"][147] = "template/default/i/osd_time.png";
$_MAG_DATA["gmode_default"][148] = "template/default/i/tv_prev_bg.png";
$_MAG_DATA["gmode_default"][149] = "template/default/i/osd_line.png";
$_MAG_DATA["gmode_default"][150] = "template/default/i/horoscope_menu_button_1_7_a.png";
$_MAG_DATA["gmode_default"][151] = "template/default/i/mb_table03.png";
$_MAG_DATA["gmode_default"][152] = "template/default/i/pause_btn.png";
$_MAG_DATA["gmode_default"][153] = "template/default/i/input_channel_bg.png";
$_MAG_DATA["gmode_default"][154] = "template/default/i/mm_vert_trans.png";
$_MAG_DATA["gmode_default"][155] = "template/default/i/mb_pass_bg.png";
$_MAG_DATA["gmode_default"][156] = "template/default/i/mm_hor_bg2.png";
$_MAG_DATA["gmode_default"][157] = "template/default/i/loading.png";
$_MAG_DATA["gmode_default"][158] = "template/default/i/_4_short_rain.png";
$_MAG_DATA["gmode_default"][159] = "template/default/i/v_menu_4.png";
$_MAG_DATA["gmode_default"][160] = "template/default/i/arr_left.png";
$_MAG_DATA["gmode_default"][161] = "template/default/i/horoscope_menu_button_1_8_b.png";
$_MAG_DATA["gmode_default"][162] = "template/default/i/mb_table02.png";
$_MAG_DATA["gmode_default"][163] = "template/default/i/bg2.png";
$_MAG_DATA["gmode_default"][164] = "template/default/i/mm_ico_radio.png";
$_MAG_DATA["gmode_default"][165] = "template/default/i/mm_ico_vidimax.png";
$_MAG_DATA["gmode_default"][166] = "template/default/i/mb_player.png";
$_MAG_DATA["gmode_default"][167] = "template/default/i/_8_rain_swon.png";
$_MAG_DATA["gmode_default"][168] = "template/default/i/loading_bg.gif";
$_MAG_DATA["gmode_default"][169] = "template/default/i/footer_search_act.png";
$_MAG_DATA["gmode_default"][170] = "template/default/i/mm_ico_oll.png";
$_MAG_DATA["gmode_default"][171] = "template/default/i/horoscope_menu_button_1_12_a.png";
$_MAG_DATA["settings_array"] = array(
	"js" => array(
		"modules" => array(
			array("name" => "lock"),
			array("name" => "lang"),
			array("name" => "update"),
			array(
				"name" => "net_info",
				"sub"  => array(
					array("name" => "wired"),
					array(
						"name" => "pppoe",
						"sub"  => array(
							array("name" => "dhcp"),
							array("name" => "dhcp_manual"),
							array("name" => "disable")
							)
						),
					array("name" => "wireless"),
					array("name" => "speed")
					)
				),
			array("name" => "video"),
			array("name" => "audio"),
			array(
				"name" => "net",
				"sub"  => array(
					array(
						"name" => "ethernet",
						"sub"  => array(
							array("name" => "dhcp"),
							array("name" => "dhcp_manual"),
							array("name" => "manual"),
							array("name" => "no_ip")
							)
						),
					array(
						"name" => "pppoe",
						"sub"  => array(
							array("name" => "dhcp"),
							array("name" => "dhcp_manual"),
							array("name" => "disable")
							)
						),
					array(
						"name" => "wifi",
						"sub"  => array(
							array("name" => "dhcp"),
							array("name" => "dhcp_manual"),
							array("name" => "manual")
							)
						)
					)
				),
			array("name" => "advanced"),
			array("name" => "dev_info"),
			array("name" => "reload"),
			array("name" => "internal_portal"),
			array("name" => "reboot")
			)
		)
	);
$_MAG_DATA["get_locales"]["English"] = "en_GB.utf8";
$_MAG_DATA["all_modules"] = array("media_browser", "tv", "apps", "dvb", "tv_archive", "time_shift", "time_shift_local", "epg.reminder", "epg.recorder", "epg", "epg.simple", "vclub", "youtube", "karaoke", "radio", "records", "remotepvr", "pvr_local", "settings.parent", "settings.localization", "settings.update", "settings.playback", "settings.common", "settings.network_status", "game.lines", "game.memory", "game.sudoku", "picasa", "settings", "weather.weatherco.day", "cityinfo", "internet");
$_MAG_DATA["switchable_modules"] = array("karaoke", "weather.day", "cityinfo", "horoscope", "horoscope", "anecdote", "game.mastermind", "infoportal");
$_MAG_DATA["disabled_modules"] = array("weather.weatherco.day", "picasa", "remotepvr", "settings.update", "settings.common", "pvr_local", "game.lines", "game.memory", "game.sudoku", "karaoke", "weather.day", "cityinfo", "horoscope", "anecdote", "game.mastermind", "infoportal");
$_MAG_DATA["restricted_modules"] = array();
$_MAG_DATA["template"] = "default";
$_MAG_DATA["get_years"] = array(
	"js" => array(
		array("id" => "*", "title" => "*"),
		array("id" => "1937", "title" => "1937"),
		array("id" => "1940", "title" => "1940"),
		array("id" => "1941", "title" => "1941"),
		array("id" => "1951", "title" => "1951"),
		array("id" => "1953", "title" => "1953"),
		array("id" => "1955", "title" => "1955"),
		array("id" => "1961", "title" => "1961"),
		array("id" => "1964", "title" => "1964"),
		array("id" => "1970", "title" => "1970"),
		array("id" => "1983", "title" => "1983"),
		array("id" => "1986", "title" => "1986"),
		array("id" => "1990", "title" => "1990"),
		array("id" => "1992", "title" => "1992"),
		array("id" => "1994", "title" => "1994"),
		array("id" => "1994/1998/2004", "title" => "1994/1998/2004"),
		array("id" => "1995", "title" => "1995"),
		array("id" => "1995/1999/2010", "title" => "1995/1999/2010"),
		array("id" => "1996", "title" => "1996"),
		array("id" => "1998", "title" => "1998"),
		array("id" => "1999", "title" => "1999"),
		array("id" => "2000", "title" => "2000"),
		array("id" => "2001", "title" => "2001"),
		array("id" => "2002", "title" => "2002"),
		array("id" => "2003", "title" => "2003"),
		array("id" => "2004", "title" => "2004"),
		array("id" => "2005", "title" => "2005"),
		array("id" => "2006", "title" => "2006"),
		array("id" => "2007", "title" => "2007"),
		array("id" => "2008", "title" => "2008"),
		array("id" => "2009", "title" => "2009"),
		array("id" => "2010", "title" => "2010"),
		array("id" => "2011", "title" => "2011"),
		array("id" => "2012", "title" => "2012"),
		array("id" => "2013", "title" => "2013"),
		array("id" => "2013", "title" => "2013"),
		array("id" => "2014", "title" => "2014")
		)
	);
$_MAG_DATA["get_abc"] = array(
	"js" => array(
		array("id" => "*", "title" => "*"),
		array("id" => "A", "title" => "A"),
		array("id" => "B", "title" => "B"),
		array("id" => "C", "title" => "C"),
		array("id" => "D", "title" => "D"),
		array("id" => "E", "title" => "E"),
		array("id" => "F", "title" => "F"),
		array("id" => "G", "title" => "G"),
		array("id" => "H", "title" => "H"),
		array("id" => "I", "title" => "I"),
		array("id" => "G", "title" => "G"),
		array("id" => "K", "title" => "K"),
		array("id" => "L", "title" => "L"),
		array("id" => "M", "title" => "M"),
		array("id" => "N", "title" => "N"),
		array("id" => "O", "title" => "O"),
		array("id" => "P", "title" => "P"),
		array("id" => "Q", "title" => "Q"),
		array("id" => "R", "title" => "R"),
		array("id" => "S", "title" => "S"),
		array("id" => "T", "title" => "T"),
		array("id" => "U", "title" => "U"),
		array("id" => "V", "title" => "V"),
		array("id" => "W", "title" => "W"),
		array("id" => "X", "title" => "X"),
		array("id" => "W", "title" => "W"),
		array("id" => "Z", "title" => "Z")
		)
	);

?>
